### ISSUE TITLE
Column start (n+1) greater than line length(n)

### ISSUE THREAD

**Issue by MattDiMu** [AtomLinter/linter-stylelint#155]
As reported in #79:

I'm experiencing the same issue with about 70% of my .scss-files, so I'm basically unable to use this (actually great) plugin. Using Win7 with the latest packages of Atom@1.7.1, linter@1.11.4, linter-stylelint@2.3.0.

One example-file, causing this error:
```
Error: Column start (2) greater than line length (1)
Error: Column start (2) greater than line length (1)
    at rangeFromLineNumber (C:\Users\xxx\.atom\packages\linter-eslint\node_modules\atom-linter\lib\index.js:194:11)
    at createRange (C:/Users/xxx/.atom/packages/linter-stylelint/lib/index.js:35:10)
    at C:/Users/xxx/.atom/packages/linter-stylelint/lib/index.js:74:14
    at Array.map (native)
    at stylelint.lint.then.error.type (C:/Users/xxx/.atom/packages/linter-stylelint/lib/index.js:70:38)

```
with the following scss-file:
```
form {
}


input, button, textarea {
  border: 1px solid $color-form-element-border;
}
```

and the following config:
```
{
  "extends": "stylelint-config-standard",
  "rules": {
    "number-leading-zero": null,
  }
}
```

When running in the command line, it actually works:
```
_form.scss
1:6     Unexpected empty block (block-no-empty)
2:3     Unexpected empty line (max-empty-lines)
5:6     Expected newline after "," (selector-list-comma-newline-after)
5:14    Expected newline after "," (selector-list-comma-newline-after)

```

Update: The numbers in the error message differ. The 1st one (start) is usually 1 higher than the line-length-number. Could this be some kind of CRLF/LF issue? (having CRLF on Windows)

**Comment by Arcanemagus** [comment]
I was just about to comment that I was unable to reproduce this until your `CRLF` comment, looking into this.

**Comment by Arcanemagus** [comment]
With the file saved as `CRLF` line endings I'm seeing exactly what you are seeing in the CLI... which is actually wrong. It's claiming that on line 2 there is an issue on character 3... when that line doesn't have that many characters.

If the file is saved as `LF` the issue doesn't show. (One could argue that the character 2 is a bug as well, since that's _technically_ the very end of the line, but it doesn't trigger this warning)

![image](https://cloud.githubusercontent.com/assets/427137/14614069/4be30382-0554-11e6-9c0b-c1e1ba968e4f.png)

Can you please file this over on the [`stylelint` repo](https://github.com/stylelint/stylelint/issues) so they can look into the real cause of this bug?

**Comment by MattDiMu** [comment]
Thx a lot for your rapid response and help. Meanwhile I've tried converting my files to LF and back to CRLF and I can confirm, that the issue seems to appear only with CRLF.
