### ISSUE TITLE
Shows error dialog while typing pseudo selector in scss

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-stylelint#183]
While typing s selector like `&:first-child`, the "unable to run stylelint"  toastr appears with `Expected pseudo-class or pseudo-element` right after typing the ":".

Shouldn't it at least show a normal inline error, which should go away once I finish typing the pseudo-selector?
![screen shot 2016-04-29 at 11 25 23 am](https://cloud.githubusercontent.com/assets/835148/14920994/dc7a9764-0dfd-11e6-9920-fab67f4cf6c4.jpg)

**Comment by Arcanemagus** [comment]
When an error like that pops up the underlying reason is that `stylelint` has `throw`n an error, and we are catching it.

_Sometimes_ the errors thrown like this have a line associated with them, in which case we just turn them into regular errors. Other times, like in this instance, there is no position associated with it so we assume it's an internal error in `stylelint` and show it to the user (Usually this is due to a configuration error instead of an internal bug).

It would really help the `stylelint` team if you could file an issue on this, narrowed down as much as possible. If you want me to take a stab at it upload the file and I'll try minimizing it down to the affected components.

Marking this as closed since it's a bug in `stylelint` and not `linter-stylelint`.
