### ISSUE TITLE
Unable to parse stylelint configuration

### ISSUE THREAD

**Issue by mdsither** [AtomLinter/linter-stylelint#291]
I'm having an error every time I try to save a file to be parsed (.scss) in Atom that I've narrowed down to linter-stylelint.

<img width="489" alt="screen shot 2016-10-13 at 12 20 40 pm" src="https://cloud.githubusercontent.com/assets/6873719/19357791/20007ef6-9141-11e6-90e5-61b086aab672.png">

 I can run `stylelint` in the command line without issues.  

<img width="558" alt="screen shot 2016-10-13 at 12 40 38 pm" src="https://cloud.githubusercontent.com/assets/6873719/19358050/49ca06de-9142-11e6-91e1-b2de3f6f8287.png">

I messed around with my config and found that when I removed the plugin `stylelint-scss` everything works fine.

I'm on a mac running 10.12
current version of Atom: 1.11.1
current version of linter-stylelint@3.4.0
current version of stylelint-scss@1.3.4
current version of stylelint@7.4.2

**Comment by Arcanemagus** [comment]
Lovely, looks like #269 is showing in a different manner with the new configuration handling.

The issue is that `stylelint-scss` has `stylelint` as a dependency of its own for some reason, and it's loading a broken version of the `table` sub-dependency. You can attempt to work around this by following https://github.com/AtomLinter/linter-stylelint/issues/269#issuecomment-248436085.

**Comment by mdsither** [comment]
Thank you @Arcanemagus
