### ISSUE TITLE
Use Stylelint Plugin

### ISSUE THREAD

**Issue by ben182** [AtomLinter/linter-stylelint#331]
Hey,

how can I use this Stylelint plugin: https://github.com/csstree/stylelint-validator?

I am using the _Use standard_ option in Atom and tried to import the plugin in the index.js in _.atom\packages\linter-stylelint\node_modules\stylelint-config-standard_
like so 
`"plugins": [
    "stylelint-csstree-validator"
  ],`
but Atom just says 
_Could not find "stylelint-csstree-validator". Do you need a `configBasedir`?_

**Comment by ninthart** [comment]
Have you tried running `npm i stylelint-validator` in your project's root directory? It's how I got stylelint-order working with linter-stylelint…

**Comment by Arcanemagus** [comment]
@ben182 You definitely shouldn't be messing with anything in this package's folder, as @ninthart stated you should be installing this in your project.

@smutnyleszek This package (and all other providers) is intended to be a way to get your existing linting setup working within Atom. It definitely _isn't_ the responsibility of this package to install things like that for you since you should already be installing it anyway.

**Comment by smutnyleszek** [comment]
@Arcanemagus I expected this, because **linter-stylelint** works perfectly without https://www.npmjs.com/package/stylelint installed, so I assumed it installs it by itself
