### ISSUE TITLE
Unable to parse stylelint configuration: Undefined rule "selector-no-id"

### ISSUE THREAD

**Issue by samuells** [AtomLinter/linter-stylelint#364]
After the update to the version 4.0.1, I am getting this bug - find no way around it. I am using json to extend standard configuration. I also did try to add "selector-no-id" into the my config file, but nothing changed. I become the same error for css or scss file.

config file: **.stylelintrc.json** is in root of the project

``` JSON
{
  "extends": "stylelint-config-sass-guidelines",
  "rules": {
    "string-quotes": "double",
    "order/properties-alphabetical-order": null,
    "order/declaration-block-properties-alphabetical-order": null,
    "max-nesting-depth": [
      3,
      {
        "ignore": [
          "blockless-at-rules"
        ]
      }
    ],
    "selector-no-qualifying-type": [
      true,
      {
        "ignore": [
          "attribute",
          "class"
        ]
      }
    ],
    "selector-class-pattern": [
      "^[a-z0-9\\-\\_]+$",
      {
        "message": "Selector should be written in lowercase with hyphens or underscores (selector-class-pattern)"
      }
    ]
  }
}
```
Settings of the plugin: 
![screenshot 2017-08-04 10 27 31](https://user-images.githubusercontent.com/5185019/28960628-bad547b2-78ff-11e7-8c2d-dbe33aebcf8f.png)

**Comment by Arcanemagus** [comment]
I'm guessing you were on a version below v4 before updating. `selector-no-id` was removed entirely in the [v8 release](https://github.com/stylelint/stylelint/releases/tag/8.0.0) of `stylelint`, which v4 updated to. It _should_ have been showing you deprecation warnings since v3.11.0 when this package was updated to `stylelint@7.12.0` when that rule was deprecated.

I would recommend updating your configuration to replace `selector-no-id` with `selector-max-id` with the primary option set to `0` as suggested in the [stylelint release](https://github.com/stylelint/stylelint/releases/tag/7.12.0).

**Comment by samuells** [comment]
Thx!
