### ISSUE TITLE
[Linter] Error running stylelint Error: Column start (40) greater than line length (31) for line 148`

### ISSUE THREAD

**Issue by geoguide** [AtomLinter/linter-stylelint#469]
This is in the atom linter package. CLI seems to work fine.

`/Users/geo/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running stylelint Error: Column start (40) greater than line length (31) for line 148`

This is driving me crazy. I tried to add some rules and then I started getting this error so I started backing out the rules and I still have the error. I've seen other closed tickets for this, but haven't seen any resolution. What is the problem?

**Comment by Arcanemagus** [comment]
Are you able to share a configuration to reproduce this? Almost always this is a bug in the linter itself, or one of the added rules in it, reporting a location that doesn't exist in the document in question.

**Comment by geoguide** [comment]
> Are you able to share a configuration to reproduce this? Almost always this is a bug in the linter itself, or one of the added rules in it, reporting a location that doesn't exist in the document in question.
```
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-styled-components"
  ],
  "syntax": "scss"
}
```

**Comment by Arcanemagus** [comment]
Sorry, that's _literally_ what I asked for, and I thank you for that. What I _meant_ though was a set of code to reproduce this on as well since errors like this are often very dependent on the content of the document.

If you are still seeing this on the current version please file a new issue with a (minimal) example code and configuration to reproduce this with, thanks!
